spring:
  application:
    name: hm
  #文件格式为 UTF-8
  messages:
    encoding: utf-8
  thymeleaf:
    cache: false
  #文件格式
  #端口号
  #server.port=8086
  # 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
     #spring.datasource.url=jdbc:mysql://127.0.0.1:3306/db2023?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://8.141.4.23:3306/db2023
    username: heavengrave
    password: czmr125?
  # 设置连接的最大生存时间为10分钟
    hikari:
      max-lifetime: 36000000
      connection-test-query: SELECT 1
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
  #websocket配置信息
  graphql:
    websocket:
      connection-init-timeout: 60s
  #图片上传相关配置 最大允许上传文件的大小。
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  #mybatisxml文件路径
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



  
