#端口号
server:
  port: 8086
spring:
  application:
    name: dream
  #文件格式为 UTF-8
  messages:
    encoding: utf-8
  # thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  #Redis
  # 数据库连接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
     #spring.datasource.url=jdbc:mysql://127.0.0.1:3306/db2023?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://8.141.4.23:3306/dream?useUnicode=true&characterEncoding=utf-8
    username: heavengrave
    password: 123456
    # 初始化连接数
    initialSize: 5
    # 最小空闲连接数
    minIdle: 5
    # 最大连接数
    maxActive: 20
    # 获取连接时最大等待时间，单位毫秒
    maxWait: 30000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 配置Druid监控页的登录用户名和密码
    statViewServlet:
      enabled: true
      url - pattern: /druid/*
      login - username: admin
      login - password: admin
    webStatFilter:
      enabled: true
      url - pattern: /*
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  #websocket配置信息
  graphql:
    websocket:
      connection-init-timeout: 60s
  #图片上传相关配置 最大允许上传文件的大小。
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: 8.141.4.23
      port: 6379
      password: 123456
      dataspace: 0
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #在控制台输出控制信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 启用 MyBatis 驼峰命名映射
    map-underscore-to-camel-case: true
